- hosts: web
  tasks:
    - name: install nginx
      ansible.builtin.apt:
        update_cache: yes
        name: nginx
        state: latest
      become: yes

    - name: update nginx config
      ansible.builtin.copy:
        src: files/nginx.conf
        dest: /etc/nginx/nginx.conf
      notify: restart nginx
      become: yes

    - name: update html
      ansible.builtin.copy:
        src: files/index.html
        dest: /usr/share/nginx/html/index.html
      become: yes

  handlers:
    - name: restart nginx
      ansible.builtin.service:
        name: nginx
        state: reloaded
      become: yes


- hosts: db 
  tasks:
    - name: update apt cache
      ansible.builtin.apt:
        update_cache: yes
      become: yes
      tags: packages

    - name: install packages
      ansible.builtin.apt:
        name: [git, make, nodejs]
        state: present
      become: yes
      tags: packages

    - name: create user arya
      ansible.builtin.user:
        name: arya
      tags: users

    - name: create user sansa
      ansible.builtin.user:
        name: sansa
      tags: users

    - name: create user tirion
      ansible.builtin.user:
        name: tirion
      tags: users

