- hosts: web
  tasks:
    - name: update apt cache
      ansible.builtin.apt:
        update_cache: yes
      become: yes
      tags: packages

    - name: install packages
      ansible.builtin.apt:
        name: [git, make, nodejs]
        state: present
      become: yes
      tags: packages

    - name: create user arya
      ansible.builtin.user:
        name: arya
      tags: users

    - name: create user sansa
      ansible.builtin.user:
        name: sansa
      tags: users

    - name: create user tirion
      ansible.builtin.user:
        name: tirion
      tags: users

