- hosts: all
  tasks:
    - name: install git (apt)
      ansible.builtin.apt: name=git state=present update_cache=yes
      when: ansible_distribution == "Ubuntu"

    - name: install git (yum)
      ansible.builtin.yum: name=git state=present
      when: ansible_distribution == "CentOS"

