- hosts: app 
  vars:
    nginx_port: 8080
    root_dir: /usr/share/nginx/html
  tasks:
    - name: install packages 
      ansible.builtin.apt:
        update_cache: yes
        name: [nginx, cowsay]
        state: latest
      become: yes

    - name: update nginx config
      ansible.builtin.template:
        src: files/nginx.conf.j2
        dest: /etc/nginx/nginx.conf
      notify: restart nginx
      become: yes

    - name: run cowsay
      ansible.builtin.command: "cowsay 'This server is {{server_name}}'"
      register: cowsay_result

    - name: update html
      ansible.builtin.template:
        src: files/index.html.j2
        dest: "{{root_dir}}/index.html" 
      become: yes

  handlers:
    - name: restart nginx
      ansible.builtin.service:
        name: nginx
        state: reloaded
      become: yes

