- name: setup user
  ansible.builtin.user:
    name: "{{name}}"
    state: "{{state}}"

- name: add git config
  when: state == "present"
  ansible.builtin.template:
    src: ../files/gitconfig.j2
    dest: "/home/{{name}}/.gitconfig"
